// src/components/LaboLink.vue
<script setup lang="ts">
import {} from 'vue'

defineProps<{
  title: string,
  id: number,
  emoji: string,
}>()
</script>

<template>
  <router-link :to="'/labo/'+id">
    <div class="rounded-md bg-white shadow-lg shadow-indigo-500/40 p-3  hover:scale-125 transition ease-in-out">
      <div class="rounded-md h-32 bg-gradient-to-r from-green-400 to-blue-500 text-clip overflow-hidden tracking-widest text-center">
        <span class="text-2xl">{{emoji.repeat(60)}}</span>
      </div>
      {{title}}
    </div>
  </router-link>
</template>

// components/LaboLink.tsx
import Link from 'next/link';

const LaboLink = ({
  id,
  emoji,
  title,
}: {
  id: string;
  emoji: string;
  title: string;
}) => {
  return (
    <Link href={`/labo/${id}`}>
      <div
        className="rounded-md bg-white p-3 shadow-lg shadow-indigo-500/40 transition ease-in-out hover:scale-105
                            dark:bg-gray-500 dark:text-white"
      >
        <div className="h-32 overflow-hidden text-clip rounded-md bg-gradient-to-r from-green-400 to-blue-500 text-center tracking-widest">
          <span className="text-2xl">{emoji.repeat(60)}</span>
        </div>
        {title}
      </div>
    </Link>
  );
};

export default LaboLink;
