// src/pages/Labo.vue
<script setup lang='ts'>
  import { ref } from 'vue'
  import LaboLink from '../components/LaboLink.vue'

  const laboLinks = ref([
    {title: '絵文字一致チャレンジ！', id: 1, emoji: '😀 '},
    {title: 'typescriptの勉強！', id: 2, emoji: 'typescript '},
    {title: 'ライクしよう！', id: 3, emoji: '❤️'},
    {title: 'ほげ', id: 2, emoji: '🦶'},
    {title: 'ほげ', id: 2, emoji: '🤖'},
    {title: 'ほげ', id: 2, emoji: '🐥'},
  ])
</script>

<template>
  <h1 class="text-2xl p-3">
    <font-awesome-icon icon="fa-solid fa-flask" />
    Labo
  </h1>

  <div class="grid grid-cols-auto-fit gap-4">
    <div v-for="link in laboLinks" :key="link.id">
      <LaboLink :title="link.title" :id="link.id" :emoji="link.emoji" />
    </div>
  </div>
</template>

// pages/labo.tsx
import Head from 'next/head';
import LaboLink from '../components/LaboLink'
import Layout from '../components/layout'
import Switch from '@/components/Switch'
import { useState } from 'react';
import { getSortedPostsData } from '@/lib/posts';
import { GetStaticProps } from 'next'

export default function FirstPost({ allPostsData }: { allPostsData: {date: string, title: string, id: string }[] }) {
  const [bool, setBool] = useState(false);

  const clickFunc = () => {
    setBool(!bool)
  }

  const laboLinks = [
    {title: '絵文字一致チャレンジ！', id: "randomEmojiChallenge", emoji: '😀 '},
    {title: 'typescriptの勉強！', id: "typescriptPractice", emoji: 'typescript '},
    {title: 'ライクしよう！', id: "3", emoji: '❤️'},
  ]

  return (
    <>
      <Head>
        <title>Labo</title>
      </Head>

      <Layout>
        <h1 className='text-2xl m-3'>ラボ</h1>

        <div className="grid grid-cols-auto-fit gap-4">
          {laboLinks.map((link) => (
            <LaboLink title={link.title} id={link.id} emoji={link.emoji} key={link.id} />
          ))}
        </div>
        <Switch bool={bool} checkedFunc={setBool} />
        <button onClick={clickFunc}>test</button>
        { bool === true ? <p>on</p> : <p>off</p> }
      </Layout>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  }
}
